### ISSUE TITLE
Some time is not available.

### ISSUE THREAD

**Issue by Macelek** [stas-demydiuk/domoticz-ewpe-smart-mqtt-plugin#1]
Hi @stas-demydiuk !

In the domoticz log communication is visible.
However the switches do not work.
The domoticz Ewpesmart Air Conditionets hardware turn off.
Thereafter.
The domoticz Ewpesmart Air Conditionets hardware turn on.
All functions work.
It takes a few hours.
Does not respond.
And then if again. I turn it off. I turn it on. All functions work.

**Comment by vapor11** [comment]
Hi,
Domoticz plugin works until reboot. When rebooted I start javascript with forever or npm but Domoticz plugin does not work anymore. What I need to do is to remove plugin from Domoticz and add it again. Then it works until next reboot. I suppose there are problems with communication between MQQT server and Domoticz plugin.

**Comment by stas-demydiuk** [comment]
@vapor11 could you please check if Domoticz with plugin starts after the bridge (npm script)

**Comment by stas-demydiuk** [comment]
@Macelek please reopen the issue if it is still valid
