### ISSUE TITLE
If my AC (Gree) is use Gree+ App, it will work with this plugin?

### ISSUE THREAD

**Issue by vampywiz17** [stas-demydiuk/domoticz-ewpe-smart-mqtt-plugin#4]
My Gree AC will install next week. The Technician say that it use Gree+ app. I check this app, but it seems to totally same with EWPE...

It will work my AC this plugin? i want to integrate it to Domoticz.

**Comment by stas-demydiuk** [comment]
Most likely it will, but you need to check to get sure

**Comment by vampywiz17** [comment]
It working :)
