### ISSUE TITLE
How to control temperature in Blocky

### ISSUE THREAD

**Issue by vapor11** [stas-demydiuk/domoticz-ewpe-smart-mqtt-plugin#5]
Is it possible to control temperature in blocky? I found only switches are controllable.

Also, this plugin works with Electrolux A/C units.

**Comment by stas-demydiuk** [comment]
@vapor11 Just checked and was able to control temperature. You just need to add device with ID `deviceID_temp` to Domoticz and go to EventsEditor: device should appear in Blocklys' Devices\SetPoint section
