### ISSUE TITLE
TOSOT AC support

### ISSUE THREAD

**Issue by pczolee** [stas-demydiuk/domoticz-ewpe-smart-mqtt-plugin#8]
Hi.

Can you support the TOSOT air conditioners as well? It is nearly the same as the Gree, the app name is TOSOT+, but it looks like ewpe. If you need any help for testing, info, debug etc, I'm ready to do it!

Thank you!

**Comment by Jan-nl** [comment]
My Tosot airco works like a charm now. Small issue in de bridge software, see the binding issue there, with the solution.

No problem with this plugin regarding this, I think this can be closed

**Comment by pczolee** [comment]
Sounds good! Can you tell me what was the issue, and where is the solution?

**Comment by Jan-nl** [comment]
Please see the issue regarding the binding in the ewpe bridge software as I already mentioned. Same developer.

**Comment by pczolee** [comment]
Ohh, I see, I found now! Thanks

**Comment by stas-demydiuk** [comment]
Now it should be fine as the original issue is closed
